CREATE TABLE person (id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                     name VARCHAR(512) NOT NULL) ;
CREATE TABLE address (id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                      person_id INT NOT NULL REFERENCES person (id),
                      address VARCHAR(1024) NOT NULL) ;

INSERT INTO person (name) VALUES ('admin') ;
INSERT INTO address (person_id, address) VALUES (1, 'home') ;
