---
- name: Build docker env
  hosts: 127.0.0.1
  connection: local
  gather_facts: no
  tags: ["{{ project_name }}-web"]
  vars:
    project_name: bodylog

  tasks:
    - name: "Build {{ project_name }}-API docker image"
      docker_image:
        name: "vpburchenya/{{ project_name }}-api"
        path: ../backend/
        dockerfile: Dockerfile
        tag: latest
        force: true
        pull: true
        push: false
      register: results_api
      notify: debug image id

    - name: "Build {{ project_name }}-WWW docker image"
      docker_image:
        name: "vpburchenya/{{ project_name }}-www"
        path: ../frontend/
        dockerfile: Dockerfile
        tag: latest
        force: true
        pull: true
        push: false
      register: results_www
      notify: debug image id

  handlers:
      - name: debug api image id
        debug:
            msg: "{{ results_api.image.Id }}"
        listen: debug image id
      - name: debug www image id
        debug:
            msg: "{{ results_www.image.Id }}"
        listen: debug image id
