FROM debian:stretch-slim AS build
LABEL maintainer="Burchenya Valentin <vp.burchenya@oz.net.ru>"


ENV WD /usr/local/app
WORKDIR $WD

COPY ./src/ ./src/

COPY ./ep.sh .
RUN chmod +x ep.sh


FROM scratch
COPY --from=build /usr/local/app /usr/local/app
# COPY ./busybox /
# volumes from use
VOLUME [/usr/local/app]

