branch-defaults:
  master:
    environment: devel
    group_suffix: null
environment-defaults:
  devel:
    branch: null
    repository: null
global:
  application_name: bodylog
  branch: null
  default_ec2_keyname: aws
  default_platform: Multi-container Docker 17.09.1-ce (Generic)  # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts.platforms.html#concepts.platforms.mcdocker
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
