---
- name: Init AWS cloud
  hosts: 127.0.0.1
  connection: local
  gather_facts: no
  tags: [aws]
  vars:
    project_name: docker
    env: staging
    aws_access_key_id:     "{{ lookup('ini', 'aws_access_key_id section=default file=~/.aws/credentials') }}"
    aws_secret_access_key: "{{ lookup('ini', 'aws_secret_access_key section=default file=~/.aws/credentials') }}"
    aws_instance_type: t2.micro
    aws_region: us-east-2
    aws_ami: ami-2eac874b

  tasks:
    - name: Show AWS key
      debug:
        msg: "{{aws_access_key_id}}:{{aws_secret_access_key}}"

    - name: Create AWS security group
      ec2_group:
        name: &sec_group_name "{{project_name}} security group"
        description: *sec_group_name
        region: "{{aws_region}}"
        # aws_access_key
        # aws_secret_key
        purge_rules: true
        purge_rules_egress: true
        purge_tags: true
        rules:
          - proto: icmp
            from_port: 8 # type
            to_port:  -1 # subtype
            cidr_ip: '0.0.0.0/0'
          - proto: tcp
            ports: 22
            cidr_ip: '0.0.0.0/0'
          - proto: tcp
            ports:
              - 80
              - 443
              - 8080-8089
            cidr_ip:
              - '0.0.0.0/0'
        rules_egress:
          - proto: all
            cidr_ip: '0.0.0.0/0'

      register: firewall  # firewall.vpc_id, .group_id
      notify: security group create

    - name: Create AWS SSH key
      ec2_key:
        name: "{{project_name}}-{{env}}-key"
        region: "{{aws_region}}"
      register: ssh_key

    # - name: Save AWS SSH key
    #   copy: content="{{ssh_key.private.key}}" dest="{{project_name}}-{{env}}-key.pem" 0400
    #   when: ssh_key.changed


  handlers:
      - name: security group create
        debug:
            msg: "Security group {{ firewall.group_id }} created or modified for VPC {{ firewall.vpc_id }}"
        when: firewall | changed
